### ISSUE TITLE
EN4 profile routine using old COAsT syntax

### ISSUE THREAD

**Issue by jpolton** [JMMP-Group/NEMO_validation#1]
Dave passed Enda some code to do EN4 comparison against AMM15 data. This used an old COAsT version before ProfileAnalysis() class separated off diagnostics.

The scripts
```
GEN_MOD_Dave_example_profile_validation.py 
mean_all_profile.TESTME.py
```
have been placed into a `work_in_progress` directory  on branch `feature/update_amm15_en4` to be updated, renamed and relocated.

Ticket can be closed and branch merged following resolution on:
* How should these files be named and stored?
* Do these files need tidying. E.g. generalising path setup.

**Comment by endaodea** [comment]
Some issues with Slowness

Working from branch * feature/update_amm15_en4

added some basic timing code, clipped to 1 month worth of P0.0 data

```python
# Say a month at a time
fn_dat = "/scratch/fred/COMPARE_VN36_VN_4.0_TIDE_SSH/%s/DAILY/%s%02d*T.nc*"%(exper,startyear,month)
```

profiles come from a file for a large range of dates:

```python
fn_prof = "/scratch/fred/EN4/SCIPY_processed_1990-2020.nc
```
(potentially this has its own problems for salinity maybe I didnt process that correctly will revisit...???)

some timing and wher the correspond in the code:

```
# Cut out a time window - to speed up obs_operator processing
profile = profile.time_slice( date0=start_date, date1=end_date )
THIS FAR B %s %s  39.90223067700572 11.975485015005688

Extracting profiles from model - is slow 
model_profiles = profile.obs_operator(nemo)
THIS FAR C.0 %s %s  197.55500899700564 157.65277831999992

# Throw away profiles where the interpolation distance is larger than 5km.
keep_indices = model_profiles.dataset.interp_dist <= 5
model_profiles = model_profiles.isel(id_dim=keep_indices)
profile = profile.isel(id_dim=keep_indices)
THIS FAR C.1 %s %s  197.59161012800178 0.03660113099613227


Model interpolated to obs locations
analysis = coast.ProfileAnalysis()
THIS FAR C.2 %s %s  197.5916525930079 4.246500611770898e-05



# Interpolate model profiles onto observation depths
model_profiles_interp = analysis.interpolate_vertical(model_profiles, profile, interp_method="linear")
print('Model interpolated to obs depths')
THIS FAR C.3 %s %s  3410.1683840220066 3212.5767314289988


# Vertical interpolation of model profiles to reference depths
model_profiles_interp_ref = analysis.interpolate_vertical(model_profiles_interp, ref_depth)
print('Model interpolated to ref depths')
THIS FAR C.4 %s %s  3618.1989423869964 208.0305583649897

Next Step it appears to fail on perhaps run out of some resource, not sure what that is.
# Interpolation of obs profiles to reference depths
profile_interp_ref = analysis.interpolate_vertical(profile, ref_depth)
```


will add sample data paths shortly on jasmin to replicate against.

**Comment by endaodea** [comment]
Sample data:

for the EN4 processed data is it available here:

```
/home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/SCIPY_processed_1990-2020.nc
```

for the P0.0 data is is available here ( a month would suffice for the above timing checks)
```
/home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/P0.0/DAILY 
```

have also copied over my modified test code for what its worth just in case the above in not decipherable.
```
~/SAMPLE_DATA_COAST_WORKFLOW/MODIFIED_work_in_prog
```
for coast the branch used is 
* develop

**Comment by jpolton** [comment]
> Sample data:
> 
> for the EN4 processed data is it available here:
> 
> ```
> /home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/SCIPY_processed_1990-2020.nc
> ```
> 
> for the P0.0 data is is available here ( a month would suffice for the above timing checks)
> 
> ```
> /home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/P0.0/DAILY 
> ```
> 
> have also copied over my modified test code for what its worth just in case the above in not decipherable.
> 
> ```
> ~/SAMPLE_DATA_COAST_WORKFLOW/MODIFIED_work_in_prog
> ```
> 
> for coast the branch used is
> 
> * develop

@endaodea I can not see modified code in `/home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/MODIFIED_work_in_prog/`. Can you send me the full path? (Code is running - wish I had implemented your timing statements...)

I am `surprised` you are working in the `feature/update_amm15_en4` branch as all the paths in `NEMO_validation/work_in_prog/GEN_MOD_Dave_example_profile_validation.py` point to my settings, which had already been edited

* Have you ever run this code on JASMIN?
* If not have you got the latest version of `NEMO_validation/work_in_prog/GEN_MOD_Dave_example_profile_validation.py` which required you to restore `fred` paths? There are a number of changes visible at ...

**Comment by endaodea** [comment]
@jpolton 

sorry must have run out of disk space mid rsync, path is :
```
/home/users/deazer/SAMPLE_DATA_COAST_WORKFLOW/MODIFIED_work_in_prog
```
For paths I just edited them back to my local space.

So a couple of questions:

Have you ever run this code on JASMIN?
* Nope

If not have you got the latest version of NEMO_validation/work_in_prog/GEN_MOD_Dave_example_profile_validation.py which required you to restore fred paths? There are a number of changes visible at https://github.com/JMMP-Group/NEMO_validation/pull/2/files

yes just switched some paths around but always possible I missed something of course.

**Comment by jpolton** [comment]
Still waiting:
```
Extracting profiles from model - is slow 
Model interpolated to obs locations
Model interpolated to obs depths
Model interpolated to ref depths
...
```


No obvious differences in the code versions. Though is an odd step where you rename bathymetry:
```
nemo.dataset = nemo.dataset.rename({"bathymetry": "bathy_metry"})
```
Though I don't think it will be problematic.


Q:Have you ever run with the `debug` flag?

```
python GEN_MOD_Dave_example_profile_validation.py P0.0 2004 MM 2005 debug
```
where MM is your integer month

**Comment by endaodea** [comment]
@jpolton  
the bathymetry renaming is a red herring it was to do with not having the bathy_metry variable present that coast desired but it make no odds,

I haven't tried the debug option....

**Comment by endaodea** [comment]
@jpolton 
ok weird with the debug option it runs through !! (yey!)
without I get a Memory error.
MemoryError: Unable to allocate 763. MiB for an array with shape (2, 51, 1345, 1458) and data type float32
note last night I explicitly created a bathy_meter variable in the domain cfg file to keep it from complaining using ncap2...

**Comment by endaodea** [comment]
@jpolton 
ill try the full profile dataset instead of the restricted debug one on a larger memory  node....

**Comment by jpolton** [comment]
> 

I'm got past  `Obs interpolated to ref depths` but still waiting...

I don't have this new `domain_cfg.nc`. Can you point me to it incase the new MES do strange things (they shouldn't)?

That array size looks like an issue with the `nemo` object rather than the `profile` object. Did it fail before the interpolation steps?

**Comment by endaodea** [comment]
@jpolton 
I am pushing the updated version of the file wit the renamed bathy_metry variable to:

/home/users/deazer/jmmp_collab/CO9_SAMPLE_DATA/P0.0

its just the default P0.0 one wit the variable renamed nothing fancy no ME issues etc.

**Comment by endaodea** [comment]
@jpolton 
the update file is in place, when I restrict in debug mode to 1000 profiles it takes about 15 minutes to run,
which seems quite a lot, for the whole set of profiles for the month as yet to get a run done. (running over 1.5hrs)

**Comment by endaodea** [comment]
@jpolton 
for the memory error when I just run it on the linux desktop  it drops out here:

```
MemoryError                               Traceback (most recent call last)
/net/data/users/fred/NEMO_validation/work_in_prog/GEN_MOD_Dave_example_profile_validation.py in <module>
    182 print("Extracting profiles from model - is slow ")
    183 
--> 184 model_profiles = profile.obs_operator(nemo)
    185 BEFORE = NOW
    186 NOW = time.perf_counter()

```

**Comment by jpolton** [comment]
OK that memory error makes sense for the desktop.
JASMIN is still grinding through the data. The interpolation steps are finished. It is now on the analysis steps.

**Comment by endaodea** [comment]
@jpolton 
Hi Jeff back online,
So ai did a quick test where I created an processed EN4 file that was just for 1 month(2004-01)
and ran as before in non debug mode with all profiles and that ran just win in 4 minutes.

I guess there are 2 options here
1. Pragmatic for now, generate a set of monthly EN4 files and batch process,
2. Better, understand why the time limit bound is not working (or appears to not work)

1. is very easy to script up just a loop over the original EN4 processing script by month, result in lots of small files

2. will probably need some input from you or Anthony as to whats going on.


Ill work on 1. so we have something to look at down the way for plots with the newer version of coast.
Its clunky but it might work for now until a proper solution is in place.
