### ISSUE TITLE
New Branches

### ISSUE THREAD

**Issue by rdPatmore** [JMMP-Group/NEMO_validation#6]
@jpolton I have a branch with the crps improvments. I am currently unable to push the branch to repository. I wonder whether this is related to some background settings.

**Comment by jpolton** [comment]
> @jpolton I have a branch with the crps improvments. I am currently unable to push the branch to repository. I wonder whether this is related to some background settings.

I can't see your branch. I guess you can not create a Pull Request. Can you send me a link to your branch. It might be something to do with permissions on JMMP-Group

**Comment by rdPatmore** [comment]
My process is to create a local branch, then add a branch to the repository by set-upstream (i.e., git branch <new_branch>; git push -u origin <new branch>). As a result, you will not be able to see my branch until it is pushed to the repository. This procedure works for CO_AMM15 (a JMMP-Group repo) and pyBDY, which suggests it may not be a JMMP-group issue, and rather a NEMO_validation one. When I look at the _branches_ page for CO_AMM15, there is a _new_branch_ button. This does not exist when I look at the same on NEMO_validation. Perhaps there are NEMO_validation settings that can be changed?

**Comment by jpolton** [comment]
NEMO_validation didn't allow the JMMP "shelf" team to maintain the repo as with CO_AMM15. Should be OK now...
